project:
  type: website

listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: false

website:
  title: "personal-site"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/guilhermeparreira
      - icon: linkedin
        href: https://www.linkedin.com/in/guilherme-parreira/
      - icon: stackoverflow
        href: https://pt.stackoverflow.com/users/33947/guilherme-parreira
      
format:
  html:
    theme:
      dark: slate
      light: yeti
    css: styles.css
    toc: true

# blog


